version: "3.9"

services:

  # Database
  simple_finances_database:
    image: "postgres:14.4-alpine"
    container_name: simple_finances_database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres
    networks:
      - net

  # Cache
  simple_finances_cache:
    image: "redis:7.0.4-alpine"
    container_name: simple_finances_cache
    restart: always
    ports:
      - ${CACHE_PORT}:6379
    environment:
      - REDIS_USER=${CACHE_USER}
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    volumes:
      - redis-data:/data/redis
    networks:
      - net

  # Application
  simple_finances_api:
    build: .
    container_name: simple_finances_api
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/node/app
    depends_on:
      - simple_finances_database
      - simple_finances_cache
    links:
      - simple_finances_database
      - simple_finances_cache
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  redis-data:
    driver: local
  pgdata:
    driver: local
