version: "3.9"

services:

  # Database
  simple_finances_database:
    image: postgres
    container_name: simple_finances_database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres
    networks:
      - net

  # Application
  simple_finances_api:
    build: .
    container_name: simple_finances_api
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/node/app
    depends_on:
      - simple_finances_database
    links:
      - simple_finances_database
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  pgdata:
    driver: local
